export const BUSINESSES = [
  {
    id: 'b1',
    name: 'سالن زیبایی نازنین',
    address: 'کرمان، بلوار حمزه، کوچه ۱۰',
    instagram: '@nazanin_beauty',
    description: 'ارائه دهنده تخصصی خدمات تراپی و کراتین مو با بهترین مواد روز دنیا در محیطی آرام و دلپذیر.',
    imageUrl: 'https://cdn.takhfifan.com/images/1.0?id=vendor/production/business/images/114603/m06a16wns0I_QQ-QOTddZA.png',
    coverUrl: 'https://cdn.takhfifan.com/images/1.0?id=vendor/production/business/images/114603/m06a16wns0I_QQ-QOTddZA.png',
    rating: 4.8,
    hasSnappPay: true,
  },
  {
    id: 'b2',
    name: 'مرکز پوست و زیبایی ماه',
    address: 'کرمان، خیابان شریعتی، مجتمع الماس',
    instagram: '@mah_skin_care',
    description: 'تخصصی ترین مرکز فیشیال و پاکسازی پوست در کرمان با استفاده از پیشرفته ترین دستگاه ها.',
    imageUrl: 'https://cdn.takhfifan.com/images/1.0?id=vendor/production/business/images/112711/rlAHNTWZQVAsCJf83C5cPw.jpeg',
    coverUrl: 'https://cdn.takhfifan.com/images/1.0?id=vendor/production/business/images/112711/rlAHNTWZQVAsCJf83C5cPw.jpeg',
    rating: 4.5,
    hasSnappPay: false,
  },
  {
    id: 'b3',
    name: 'سالن زیبایی آوینا',
    address: 'کرمان، هزار و یک شب، بین کوچه ۵ و ۷',
    instagram: '@avina_nail',
    description: 'خدمات حرفه ای ناخن، مانیکور و پدیکور با جدیدترین متدها و تنوع رنگی بی نظیر.',
    imageUrl: 'https://cdn.takhfifan.com/images/1.0?id=vendor/production/business/images/101015/0ZuchDERMPxI4pMcFTOAcQ.PNG',
    coverUrl: 'https://cdn.takhfifan.com/images/1.0?id=vendor/production/business/images/101015/0ZuchDERMPxI4pMcFTOAcQ.PNG',
    rating: 4.7,
    hasSnappPay: true,
  },
  {
    id: 'b4',
    name: 'کلینیک زیبایی یاس',
    address: 'کرمان، پارک نو، نبش کوچه ۱۲',
    instagram: '@yas_clinic',
    description: 'کلینیک تخصصی پوست و مو، فیشیال تخصصی و جوانسازی تحت نظر پزشک متخصص.',
    imageUrl: 'https://cdn.takhfifan.com/images/1.0?id=vendor/production/business/images/63317/ZBr69rE1oRKzOnGOvOpnsw.JPG',
    coverUrl: 'https://cdn.takhfifan.com/images/1.0?id=vendor/production/business/images/63317/ZBr69rE1oRKzOnGOvOpnsw.JPG',
    rating: 4.9,
    hasSnappPay: true,
  },
  {
    id: 'b5',
    name: 'سالن زیبایی نیلا',
    address: 'کرمان، بلوار جمهوری، کوچه ۱۸',
    instagram: '@nila_haircolor',
    description: 'تخصص در رنگ و لایت، آمبره و سامبره با تکنیک های روز و مواد بدون آسیب.',
    imageUrl: 'https://cdn.takhfifan.com/images/1.0?id=vendor/production/business/images/119592/12jb-WdhETVbGlNIe5LvKw.png',
    coverUrl: 'https://cdn.takhfifan.com/images/1.0?id=vendor/production/business/images/119592/12jb-WdhETVbGlNIe5LvKw.png',
    rating: 4.6,
    hasSnappPay: false,
  },
  {
    id: 'b6',
    name: 'مرکز مراقبت پوست آیلین',
    address: 'کرمان، خیابان والفجر، ساختمان پزشکان آفتاب',
    instagram: '@aylin_skincare',
    description: 'ارائه دهنده خدمات مزوتراپی، میکرونیدلینگ و جوانسازی پوست به صورت کاملا تخصصی.',
    imageUrl: 'https://cdn.takhfifan.com/images/1.0?id=vendor/production/business/images/100410/xvM7_dHdgzyAGCYKcqmRTQ.jpg',
    coverUrl: 'https://cdn.takhfifan.com/images/1.0?id=vendor/production/business/images/113533/a0jQueHo7JDieIhR5cCdHw.jpg',
    rating: 4.4,
    hasSnappPay: true,
  },
];

export const DEALS = [
  {
    id: 'd1',
    businessId: 'b1',
    businessName: 'سالن زیبایی نازنین',
    serviceTitle: 'کراتین و احیای مو',
    originalPrice: 2500000,
    discountedPrice: 1750000,
    discountPercentage: 30,
    expiryDate: '۱۴۰۵/۰۳/۱۵',
    imageUrl: 'https://cdn.takhfifan.com/images/1.0?id=vendor/production/business/images/117237/q9pQJ20OMz4bs5UEI3sTxw.png',
    category: 'hair',
  },
  {
    id: 'd1_2',
    businessId: 'b1',
    businessName: 'سالن زیبایی نازنین',
    serviceTitle: 'براشینگ تخصصی',
    originalPrice: 300000,
    discountedPrice: 150000,
    discountPercentage: 50,
    expiryDate: '۱۴۰۵/۰۳/۱۵',
    imageUrl: 'https://cdn.takhfifan.com/images/1.0?id=vendor/production/business/images/19784/yNLgDEW2fsDJtEnOysY8Hw.JPG',
    category: 'hair',
  },
  {
    id: 'd2',
    businessId: 'b2',
    businessName: 'مرکز پوست و زیبایی ماه',
    serviceTitle: 'پاکسازی و فیشیال کلاسیک',
    originalPrice: 850000,
    discountedPrice: 595000,
    discountPercentage: 30,
    expiryDate: '۱۴۰۵/۰۳/۲۰',
    imageUrl: 'https://cdn.takhfifan.com/images/1.0?id=vendor/production/business/images/119274/cuPnkiN-jZKsUJeLU08UEw.jpg',
    category: 'skin',
  },
  {
    id: 'd2_2',
    businessId: 'b2',
    businessName: 'مرکز پوست و زیبایی ماه',
    serviceTitle: 'ماساژ صورت هیدرودرمی',
    originalPrice: 500000,
    discountedPrice: 300000,
    discountPercentage: 40,
    expiryDate: '۱۴۰۵/۰۳/۲۰',
    imageUrl: 'https://cdn.takhfifan.com/images/1.0?id=vendor/production/business/images/114348/cnOIHeAIc43Edf8365_CWg.jpg',
    category: 'skin',
  },
  {
    id: 'd3',
    businessId: 'b3',
    businessName: 'سالن زیبایی آوینا',
    serviceTitle: 'مانیکور و پدیکور VIP',
    originalPrice: 450000,
    discountedPrice: 315000,
    discountPercentage: 30,
    expiryDate: '۱۴۰۵/۰۳/۲۵',
    imageUrl: 'https://cdn.takhfifan.com/images/1.0?id=vendor/production/business/images/116589/CesTTYgGoMC8Ylo-gV-Pww.png',
    category: 'nail',
  },
  {
    id: 'd3_2',
    businessId: 'b3',
    businessName: 'سالن زیبایی آوینا',
    serviceTitle: 'ژلیش ناخن دست',
    originalPrice: 200000,
    discountedPrice: 100000,
    discountPercentage: 50,
    expiryDate: '۱۴۰۵/۰۳/۲۵',
    imageUrl: 'https://cdn.takhfifan.com/images/1.0?id=vendor/production/business/images/119592/12jb-WdhETVbGlNIe5LvKw.png',
    category: 'nail',
  },
  {
    id: 'd3_3',
    businessId: 'b3',
    businessName: 'سالن زیبایی آوینا',
    serviceTitle: 'کاشت ناخن پودری',
    originalPrice: 600000,
    discountedPrice: 420000,
    discountPercentage: 30,
    expiryDate: '۱۴۰۵/۰۳/۲۵',
    imageUrl: 'https://cdn.takhfifan.com/images/1.0?id=vendor/production/business/images/115355/KFtkvFbzrwCQDMOYmPHhfg.jpg',
    category: 'nail',
  },
  {
    id: 'd3_4',
    businessId: 'b3',
    businessName: 'سالن زیبایی آوینا',
    serviceTitle: 'پارافین تراپی دست',
    originalPrice: 300000,
    discountedPrice: 210000,
    discountPercentage: 30,
    expiryDate: '۱۴۰۵/۰۳/۲۵',
    imageUrl: 'https://cdn.takhfifan.com/images/1.0?id=vendor/production/business/images/90368/XANnPRPgHoVjIpP09iwsRw.png',
    category: 'nail',
  },
  {
    id: 'd4',
    businessId: 'b4',
    businessName: 'کلینیک زیبایی یاس',
    serviceTitle: 'فیشیال تخصصی جوانسازی',
    originalPrice: 1200000,
    discountedPrice: 840000,
    discountPercentage: 30,
    expiryDate: '۱۴۰۵/۰۳/۱۰',
    imageUrl: 'https://cdn.takhfifan.com/images/1.0?id=vendor/production/business/images/47238/ogj6AjDUjwwsqm9bbsEECQ.png',
    category: 'medical',
  },
  {
    id: 'd4_2',
    businessId: 'b4',
    businessName: 'کلینیک زیبایی یاس',
    serviceTitle: 'تزریق بوتاکس مصپورت',
    originalPrice: 1500000,
    discountedPrice: 900000,
    discountPercentage: 40,
    expiryDate: '۱۴۰۵/۰۳/۱۰',
    imageUrl: 'https://cdn.takhfifan.com/images/1.0?id=vendor/production/business/images/117349/50IRyc0IlOeWwY0QBfhMkg.JPG',
    category: 'medical',
  },
  {
    id: 'd5',
    businessId: 'b5',
    businessName: 'سالن زیبایی نیلا',
    serviceTitle: 'رنگ و لایت تخصصی',
    originalPrice: 3500000,
    discountedPrice: 2450000,
    discountPercentage: 30,
    expiryDate: '۱۴۰۵/۰۴/۰۱',
    imageUrl: 'https://cdn.takhfifan.com/images/1.0?id=vendor/production/business/images/100410/xvM7_dHdgzyAGCYKcqmRTQ.jpg',
    category: 'hair',
  },
  {
    id: 'd6',
    businessId: 'b6',
    businessName: 'مرکز مراقبت پوست آیلین',
    serviceTitle: 'مزوتراپی مو سر',
    originalPrice: 1800000,
    discountedPrice: 1260000,
    discountPercentage: 30,
    expiryDate: '۱۴۰۵/۰۳/۳۰',
    imageUrl: 'https://cdn.takhfifan.com/images/1.0?id=96191/production/package/images/264996/nxsts6x3_HGcrdKViRJJrQ.png',
    category: 'medical',
  },
];